<a href="https://colab.research.google.com/github/nehaverma13/problem-solving-using-numpy/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##write a Numpy program to multiply a 5*3 matrix by a 3*2 matrix and create a real matrix product

In [ ]:
import numpy as np
arr1= np.random.random((5,3))
print("first array :")
print(arr1)
arr2=np.random.random((3,2))
print("second array:")
print(arr2)
arr3=np.dot(arr1,arr2)
print("dot product of two array:")
print(arr3)


first array :
[[0.57444036 0.24592197 0.89759831]
 [0.91614544 0.71529703 0.58267364]
 [0.46630336 0.24209527 0.65512189]
 [0.16832756 0.00908886 0.46796793]
 [0.04078163 0.60894664 0.47475153]]
second array:
[[0.58749134 0.72792329]
 [0.76518851 0.73482157]
 [0.64596555 0.00250212]]
dot product of two array:
[[1.10547299 0.60110318]
 [1.46195168 1.19395721]
 [0.88238388 0.51896909]
 [0.40813684 0.13037915]
 [0.79659096 0.47834091]]


### Write a NumPy program to check if each element of an array of your
###choice is composed of digits, lower case letters, and upper case letters only

In [ ]:
ar=np.array(['Python','PHP','JS','Examples','html5','5'])
            

In [ ]:
ar

array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype='<U8')

In [ ]:
print("original array:",ar)

original array: ['Python' 'PHP' 'JS' 'Examples' 'html5' '5']


In [ ]:
c1=np.char.isdigit(ar)
c2=np.char.islower(ar)
c3=np.char.isupper(ar)
print("digits only=",c1)
print("lowercase only=",c2)
print("uppercase only=",c3)

digits only= [False False False False False  True]
lowercase only= [False False False False  True False]
uppercase only= [False  True  True False False False]


###Write a program that reads two space-separated positive integers 𝑋 and
###𝑌 as input and perform the following tasks:
Tasks to be performed:
1. Create a list (lst1) starting at one (1) with 16 elements at a step of 𝑋
2. Create a list (lst2) starting at one (1) with 16 elements at a step of 𝑌
3. Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
4. Reshape both the NumPy arrays to (4,4)
5. Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -
np2)
6. Print all the elements of np3 in a single dimension list like the format as shown below:
a. [n0 n1 n2 n3 n4 n5 n6 n7 n8]

In [17]:
import numpy as np
x,y=input("enter two space-separated positive integer x and y").split(" ")
print("x=",int(x))
print("y=",int(y))
z=(16*int(x))+1
w=(16*int(y))+1
lst1=list(range(1,z,int(x)))
lst2=list(range(1,w,int(y)))
print(lst1)
print(lst2)

enter two space-separated positive integer x and y7 9
x= 7
y= 9
[1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99, 106]
[1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91, 100, 109, 118, 127, 136]


In [20]:
np1=np.array([lst1])
np1

array([[  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,
         92,  99, 106]])

In [21]:
np2=np.array([lst2])
np2

array([[  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100, 109,
        118, 127, 136]])

In [18]:
twonumpyarr=([lst1],[lst2])

In [19]:
twonumpyarr

([[1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99, 106]],
 [[1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91, 100, 109, 118, 127, 136]])

In [22]:
ar1=np1.reshape((4,4))

In [23]:
ar1

array([[  1,   8,  15,  22],
       [ 29,  36,  43,  50],
       [ 57,  64,  71,  78],
       [ 85,  92,  99, 106]])

In [24]:
ar2=np2.reshape((4,4))

In [25]:
ar2

array([[  1,  10,  19,  28],
       [ 37,  46,  55,  64],
       [ 73,  82,  91, 100],
       [109, 118, 127, 136]])

In [26]:
ar1=np.array([[[[1,8,15,22],[29,36,43,50],[57,64,71,78],[85,92,99,106]]]])
ar2=np.array([[[[1,10,19,28],[37,46,55,64],[73,82,91,100],[109,118,127,136]]]])
np3=np.subtract(ar1,ar2)


In [27]:
np3

array([[[[  0,  -2,  -4,  -6],
         [ -8, -10, -12, -14],
         [-16, -18, -20, -22],
         [-24, -26, -28, -30]]]])

###: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of shape [3 ∗ 3] and perform the following task:
###Task to be performed Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄).

In [47]:
P=np.array([23,56,87,3,6, 96, 4, 6, 78])
P

array([23, 56, 87,  3,  6, 96,  4,  6, 78])

In [48]:
Q=np.array([12,34,54 ,7, 2, 54, 6, 2, 78])
Q

array([12, 34, 54,  7,  2, 54,  6,  2, 78])

In [49]:
minus=np.subtract(P,Q)

In [ ]:
arr=np.array([[[11,22,33],[-4,4,42],[-2,4,0]]])
arr

array([[[11, 22, 33],
        [-4,  4, 42],
        [-2,  4,  0]]])